##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See ansible-nas/group_vars/all.yml 
# and ./group_vars/all.yml for all possible settings.

no_log: false

# Location of essential storage. Using the same pool name as FreeNAS.
zfs_root: "/vol1"

samba_shares_root: "{{ zfs_root }}/larsonmedia"
downloads_root: "{{ samba_shares_root }}/downloads"

# Set our host name from the environment if defined. This is for the
# test server so the computer names don't collide on the LAN.
our_host_name: "{{ lookup('env', 'ANSIBLE_HOST_NAME_OVERRIDE') | default('nas', true) }}"

# System options.
ansible_nas_hostname: "{{ our_host_name }}"
ansible_nas_user: skb
ansible_nas_email: dlarson42@gmail.com
ansible_nas_domain: dilbertshrugged.com
ansible_nas_timezone: America/Chicago

samba_workgroup: LARZVILLE
samba_netbios_name: "{{ our_host_name }}"

# Enable the reverse proxy for external access.
traefik_enabled: true

# Enable some applications.
heimdall_enabled: true
portainer_enabled: true
glances_enabled: true
#netdata_enabled: true
sabnzbd_enabled: true

guacamole_enabled: true
guacamole_available_externally: "true"

# sabnzbd settings.
sabznbd_enabled: true
sabnzbd_default_directory: "{{ docker_home }}/sabnzbd/data"
sabnzbd_data_directory: "{{ lookup('env', 'ANSIBLE_SABNZBD_DATA_OVERRIDE') | default(lookup('vars', 'sabnzbd_default_directory'), true) }}"
sabnzbd_downloads_directory: "{{ sabnzbd_data_directory }}/downloads"
sabnzbd_incomplete_directory: "{{ sabnzbd_data_directory }}/sabnzbd-incomplete"
sabnzbd_user_id: "1001"
sabnzbd_group_id: "1001"

# transmission settings.
transmission_enabled: true
transmission_default_download_directory: "{{ docker_home }}/transmission"
transmission_download_directory: "{{ lookup('env', 'ANSIBLE_TRANSMISSION_DLOAD_OVERRIDE') | default(lookup('vars', 'transmission_default_download_directory'), true) }}"
transmission_user_id: "1001"
transmission_group_id: "1001"

# Gitlab defn's
gitlab_enabled: false
gitlab_data_directory: "{{ zfs_root }}/gitdata/gitlab"
gitlab_available_externally: "false"
gitlab_user_id: "998"
gitlab_group_id: "998"

# Ansible-vault defined passwords for Samba.
dlarson_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30613861656134343330396436386432346131376434613837343939383336373935393161363666
          3338373432653536653236346633366162666638393163640a666632373732343736653633363439
          36306665333736616337323335393365613434356336313065316261363333396561393333383566
          3039373633633537320a313136333961386139376431666463653131373234313261386363353434
          3532

jlarson_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30613861656134343330396436386432346131376434613837343939383336373935393161363666
          3338373432653536653236346633366162666638393163640a666632373732343736653633363439
          36306665333736616337323335393365613434356336313065316261363333396561393333383566
          3039373633633537320a313136333961386139376431666463653131373234313261386363353434
          3532

larzmedia_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64333539633961333762396663663139333537313431306131333635386566636636656231646335
          3538643732303331306235323261663832326565353163310a663233303330373534373133313061
          35326135333661346435373965636637346431366233633262356130393232663030653461373038
          3261393638313761650a326562303464323636343037373863616539363961346337313262373235
          66396466646536313332386561633834633636336238313166306637316339363462

larzmediaro_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61626465626637303962613234316566313365336435336433633435613663333530616263353165
          3236623565623134633935303935626134653065386633380a623865346334356134653764303136
          31306137323462386233616665363536623634636632613461353332326561653663353733303962
          3162666639646635330a633134383633326336353065316138303934663364356238346264653334
          3839

# System backup Samba shares are stored here.
ibackup_root: "{{ zfs_root }}/backups/ivanbackup"

jbackup_root: "{{ zfs_root }}/backups/judebackup"

# Network backed directories for us. 
dlarson_root: "{{ zfs_root }}/home/dlarson"

jlarson_root: "{{ zfs_root }}/home/jlarson"

# Media related Samba shares are stored here.
larzmedia_root: "{{ samba_shares_root }}"

books_root: "{{ samba_shares_root }}/books"

music_root: "{{ samba_shares_root }}/music"

photos_root: "{{ samba_shares_root }}/photos"

videos_root: "{{ samba_shares_root }}/videos"

# The passwords refer to variables protected by ansible-vault.
samba_users:
  - name: dlarson
    password: "{{ dlarson_passwd }}"
  - name: jlarson
    password: "{{ jlarson_passwd }}"
  - name: larzmedia
    password: "{{ larzmedia_passwd }}"
  - name: larzmediaro
    password: "{{ larzmediaro_passwd }}"

# Define our Samba shares.
samba_shares:
  - name: ibackup
    comment: "IVANs backups"
    public: no
    browsable: yes
    valid_users: dlarson
    write_list: dlarson
    group: ansible-nas
    path: "{{ ibackup_root }}"

  - name: jbackup
    comment: "Judes backups"
    public: no
    browsable: yes
    valid_users: dlarson, jlarson
    write_list: dlarson, jlarson
    group: ansible-nas
    path: "{{ jbackup_root }}"

  - name: dlarson
    comment: "Dales shared workspace"
    public: no
    browsable: yes
    valid_users: dlarson
    write_list: dlarson
    group: ansible-nas
    path: "{{ dlarson_root }}"

  - name: jlarson
    comment: "Judes shared workspace."
    public: no
    browsable: yes
    valid_users: jlarson, dlarson
    write_list: jlarson, dlarson
    group: ansible-nas
    path: "{{ jlarson_root }}"

  - name: larzmedia
    comment: "Overall access to family media"
    public: no
    browsable: yes
    valid_users: larzmedia, dlarson
    write_list: larzmedia, dlarson, jlarson
    group: ansible-nas
    path: "{{ larzmedia_root }}"

  - name: books
    public: no
    readonly: yes
    browsable: yes
    valid_users: larzmediaro, @ansible-nas
    group: ansible-nas
    path: "{{ books_root }}"

  - name: music
    public: no
    readonly: yes
    browsable: yes
    valid_users: larzmediaro, @ansible-nas
    group: ansible-nas
    path: "{{ music_root }}"
 
  - name: photos
    public: no
    readonly: yes
    browsable: yes
    valid_users: larzmediaro, @ansible-nas
    group: ansible-nas
    path: "{{ photos_root }}"
 
  - name: torrents
    public: no
    readonly: yes
    browsable: yes
    valid_users: dlarson, @ansible-nas
    write_list: dlarson, @ansible-nas
    group: ansible-nas
    path: "{{ torrents_root }}"
 
  - name: videos
    public: no
    readonly: yes
    browsable: yes
    valid_users: larzmediaro, @ansible-nas
    group: ansible-nas
    path: "{{ videos_root }}"
